// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace PRN222_Assignment_01.Models;

[Table("Tag")]
public partial class Tag
{
    [Key]
    public int TagID { get; set; }

    [StringLength(50)]
    public string TagName { get; set; }

    [StringLength(400)]
    public string Note { get; set; }

    [InverseProperty("Tag")]
    public virtual ICollection<NewsTag> NewsTags { get; set; } = new List<NewsTag>();
}